apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dml-sw-vol
  namespace: ucsd-digital-media-lab
spec:
  storageClassName: seaweedfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
