apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dml2-sw-vol
  namespace: ucsd-digital-media-lab
spec:
  storageClassName: seaweedfs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500gb
